### ISSUE TITLE
Support for Gnome 45

### ISSUE THREAD

**Issue by thomasaull** [troyready/quarterwindows#9]
Love this extension, thanks for creating it! Would it be as easy as just adding Gnome 45 to the compatibility metadata to make it work?

**Comment by rtpt-lucasvater** [comment]
I currently have this extension running on GNOME 45 with the changes I made in #10. There are some code changes needed to make it work on GNOME 45, since they changed how modules are imported (detailed in https://gjs.guide/extensions/upgrading/gnome-shell-45.html). 

The Pull-Request also contains some more changes to how the extension moves windows internally that worked better in my case.
